language: python
python:
  - "3.6"

# Install dependencies.
install:
  - sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n

before_script:

# Run linting and tests.
script:
  - state run lints
  - state run tests

# Turn email notifications off.
notifications:
  email: false
