language: python
python:
  - "3.6"

# Install dependencies.
install:
  - sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n

before_script:
  - export VERBOSE=true
  - state activate

# Run linting and tests.
script:
  - pylint ./src
  - flake8 ./src --statistics --count
  - pytest

# Turn email notifications off.
notifications:
  email: false
