version: 1.0.{build}
image: Visual Studio 2019
init:
- ps: ''
install:
- ps: >-
    Set-Item -Path Env:NOPROMPT_INSTALL -Value 'true'
    
    IEX (New-Object Net.WebClient).downloadString('https://platform.activestate.com/dl/cli/install.ps1')
    
build_script:
- cmd: state --version
test_script:
- cmd: >-
    state run lints

    state run tests
