# Python application example with ActiveState Platform

trigger:
- activestate-platform-and-state-tool-setup
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n
    displayName: 'Install State Tool'
  - script: state deploy MyOrg/learn-python
    displayName: 'Deploy project'
  - script: pylint src
    displayName: 'Lint with pylint'
  - script: flake8 src --statistics --count
    displayName: 'Lint with flake8'
  - script: pytest
    displayName: 'Test with pytest'
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n
    displayName: 'Install State Tool'
  - script: state deploy MyOrg/learn-python
    displayName: 'Deploy project'
  - script: pylint src
    displayName: 'Lint with pylint'
  - script: flake8 src --statistics --count
    displayName: 'Lint with flake8'
  - script: pytest
    displayName: 'Test with pytest'
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo hello from Windows    
