# Python application example with ActiveState Platform

trigger:
- activestate-platform-and-state-tool-setup
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n
    displayName: 'Install State Tool'
  - script: state deploy MyOrg/learn-python
    displayName: 'Deploy project'
  - script: pylint src
    displayName: 'Lint with pylint'
  - script: flake8 src --statistics --count
    displayName: 'Lint with flake8'
  - script: pytest
    displayName: 'Test with pytest'
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n
    displayName: 'Install State Tool'
  - script: |
      echo $AGENT_BUILDDIRECTORY
      echo $AGENT_HOMEDIRECTORY
      echo $AGENT_TEMPDIRECTORY
      echo $AGENT_TOOLSDIRECTORY
      echo $AGENT_WORKFOLDER
      export PATH=$PIPELINE_WORKSPACE/bin:$PATH 
      export SHELL=bash
      echo $PATH
      state deploy MyOrg/learn-python
    displayName: 'Deploy project'
  - script: pylint src
    displayName: 'Lint with pylint'
  - script: flake8 src --statistics --count
    displayName: 'Lint with flake8'
  - script: pytest
    displayName: 'Test with pytest'
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - bash: sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n
    displayName: 'Install State Tool'
  - bash: |
      export SHELL=bash
      state deploy MyOrg/learn-python
    displayName: 'Deploy project'
  - bash: pylint src
    displayName: 'Lint with pylint'
  - bash: flake8 src --statistics --count
    displayName: 'Lint with flake8'
  - bash: pytest
    displayName: 'Test with pytest'
