steps:
- name: docker.io/activestate/state_gcb
  args: ['state','auth']
- name: docker.io/activestate/state_gcb
  args: ['state', 'deploy', 'shnewto/learn-python', '--path', '/workspace/.state']
- name: docker.io/activestate/state_gcb
  args: ['pylint','src']
- name: docker.io/activestate/state_gcb
  args: ['flake8','src','--statistics','--count']
- name: docker.io/activestate/state_gcb
  args: ['pytest']
options:
  env:
  - 'ACTIVESTATE_CLI_DISABLE_UPDATES=true'
  - 'PATH=/workspace/.state/07952536/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
