steps:
- name: docker.io/activestate/state_gcb
  args: ['state', '--version']
- name: docker.io/activestate/state_gcb
  args: ['state', 'deploy', 'shnewto/learn-python', '--path', '/workspace/.state']
- name: docker.io/activestate/state_gcb
  args: ['bash', '-c', 'pylint src && flake8 src --statistics --count']
- name: docker.io/activestate/state_gcb
  args: ['pytest']
artifacts:
  objects:
    location: 'gs://activestate_test_artifacts/'
    paths: ['output']
options:
  env:
  - 'ACTIVESTATE_CLI_DISABLE_UPDATES=true'
