steps:
- name: docker.io/activestate/state_gcb
  args: ['state','auth']
- name: docker.io/activestate/state_gcb
  args: ['state', 'deploy', 'shnewto/learn-python', '--path', '/workspace/.state']
- name: docker.io/activestate/state_gcb
  args: ['pylint','src']
- name: docker.io/activestate/state_gcb
  args: ['flake8','src','--statistics','--count']
- name: docker.io/activestate/state_gcb
  args: ['pytest']
