steps:
- name: docker.io/activestate/state_gcb	
  args: ['bash', '-c', 'env']
- name: docker.io/activestate/state_gcb
  args: ['state', 'deploy', 'shnewto/learn-python', '--path', '/workspace/.state']
- name: docker.io/activestate/state_gcb	
  args: ['bash', '-c', 'env']
- name: docker.io/activestate/state_gcb	
  args: ['pytest']
  env: 
  - 'PATH=/workspace/.state/bin'
- name: docker.io/activestate/state_gcb
  args: ['.state/07952536/bin/pylint','src']
- name: docker.io/activestate/state_gcb
  args: ['.state/07952536/bin/flake8','src','--statistics','--count']
- name: docker.io/activestate/state_gcb
  args: ['.state/07952536/bin/pytest']
options:
  env:
  - 'ACTIVESTATE_CLI_DISABLE_UPDATES=true'
  - 'PATH=$PATH:/workspace/.state/bin'
