name: ActivePython application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install State Tool (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run:  (New-Object Net.WebClient).DownloadFile('https://platform.activestate.com/dl/cli/install.ps1', 'install.ps1')
    - name: Install State Tool (Linux&Mac)            
      if: matrix.os != 'windows-latest'      
      run: sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n  
    - name: Lint with flake8
      run: state run lints
    - name: Test with pytest
      run: state run tests
