name: ActivePython application

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install State Tool (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Get-ChildItem Env:GITHUB_WORKSPACE
        Get-Location
        (New-Object Net.WebClient).DownloadFile('https://platform.activestate.com/dl/cli/install.ps1', 'install.ps1'); 
        Invoke-Expression -Command "D:\a\learn-python\learn-python\install.ps1 -n"
      shell: powershell
    - name: Install State Tool (Linux&Mac)            
      if: matrix.os != 'windows-latest'      
      run: sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n  
    - name: Lint with flake8
      env: # Or as an environment variable
        ACTIVESTATE_API_KEY: ${{ secrets.ACTIVESTATE_API_KEY }}  
      run: state run lints
    - name: Test with pytest
      run: state run tests
