name: ActivePython application

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install State Tool (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        (New-Object Net.WebClient).DownloadFile('https://platform.activestate.com/dl/cli/install.ps1', 'install.ps1'); 
        Invoke-Expression -Command "$Env:GITHUB_WORKSPACE\install.ps1 -n -t $Env:GITHUB_WORKSPACE"
      shell: powershell
    - name: Lint with flake8 (Windows)
      if: matrix.os == 'windows-latest'
      env: # Or as an environment variable
        ACTIVESTATE_API_KEY: ${{ secrets.ACTIVESTATE_API_KEY }}  
      run: |
        Set-Location -Path $Env:GITHUB_WORKSPACE
        Invoke-Expression -Command "$Env:GITHUB_WORKSPACE\state.exe run lints"
    - name: Test with pytest (Windows)
      if: matrix.os == 'windows-latest'
      env: # Or as an environment variable
        ACTIVESTATE_API_KEY: ${{ secrets.ACTIVESTATE_API_KEY }}  
      run: |
        Set-Location -Path $Env:GITHUB_WORKSPACE
        Invoke-Expression -Command "$Env:GITHUB_WORKSPACE\state.exe run tests"
    - name: Install State Tool (Linux&Mac)            
      if: matrix.os != 'windows-latest'      
      run: sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n
    - name: Lint with flake8 (Linux&Mac)
      if: matrix.os != 'windows-latest'
      run: state run lints
    - name: Test with pytest (Linux&Mac)
      if: matrix.os != 'windows-latest'
      env: # Or as an environment variable
        ACTIVESTATE_API_KEY: ${{ secrets.ACTIVESTATE_API_KEY }}  
      run: state run tests
        
