name: ActivePython application

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install State Tool (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        powershell IEX(New-Object Net.WebClient).DownloadFile('https://platform.activestate.com/dl/cli/install.ps1', '$GITHUB_WORKSPACE\install.ps1')
        powershell Invoke-Expression "$GITHUB_WORKSPACE\install.ps1 -n"
      shell: cmd
    - name: Install State Tool (Linux&Mac)            
      if: matrix.os != 'windows-latest'      
      run: sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n  
    - name: Lint with flake8
      env: # Or as an environment variable
        ACTIVESTATE_API_KEY: ${{ secrets.ACTIVESTATE_API_KEY }}  
      run: state run lints
    - name: Test with pytest
      run: state run tests
